In [3]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_excel("C:\Amine\Projects\Delivery company\Data_livraison.xlsx")

In [3]:
df.head()

Tracking Référence            Client   Téléphone  \
0  EC0EEE25042244440       NaN  Belguidoum Rahma  0666741187   
1  EC0EEE25050445827       NaN              SETO   041747668   
2  EC0EEE25050646042       NaN           sorfert  0550362092   
3  EC0EEE25050646061       NaN      AKNI Zakaria  0770388685   
4  EC0EEE25051547274       NaN         SONATRACH  0771655090   

                                             Adresse      Commune  \
0                           Draa limam ilot 575 N 12      Tebessa   
1            BP 9977 El-Makkari 31007 Oran - Algérie         Oran   
2                     complexe d'ammoniac et d'urée,        Arzew   
3           Cité AADL 2000 LGTS BT42 N02-ALI Mendjli  Constantine   
4  Bp 9671 rue DJELLOUL BAKHTI NEMMICHE rond poin...         Oran   

        Wilaya Remarque    Produit  Montant  ... Versé à l'admin le Payé le  \
0      Tébessa      NaN   DOCUMENT        0  ...                NaN     NaN   
1         Oran      NaN   Document        0  ...                NaN     NaN   
2         Oran      NaN   document        0  ...                NaN     NaN   
3  Constantine      NaN   Document        0  ...                NaN     NaN   
4         Oran      NaN  DOCUMENTS        0  ...                NaN     NaN   

  Archivé le Retour demandé le Transféré vers l'admin le  Reçu par l'admin le  \
0        NaN               NaN                       NaN     03-05-2025 14:14   
1        NaN               NaN                       NaN     15-05-2025 13:13   
2        NaN               NaN                       NaN     12-05-2025 14:30   
3        NaN               NaN                       NaN     22-05-2025 11:42   
4        NaN               NaN                       NaN     26-05-2025 16:15   

  Transféré au partenaire le Colis facturé  Statut  SMS envoyés  
0                        NaN           NaN   livré          NaN  
1                        NaN           NaN   livré          NaN  
2                        NaN           NaN   livré          NaN  
3                        NaN           NaN   livré          NaN  
4                        NaN           NaN   livré          NaN  

[5 rows x 54 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28047 entries, 0 to 28046
Data columns (total 54 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Tracking                                28047 non-null  object 
 1   Référence                               15628 non-null  object 
 2   Client                                  28047 non-null  object 
 3   Téléphone                               28047 non-null  object 
 4   Adresse                                 28038 non-null  object 
 5   Commune                                 28047 non-null  object 
 6   Wilaya                                  28047 non-null  object 
 7   Remarque                                4788 non-null   object 
 8   Produit                                 28047 non-null  object 
 9   Montant                                 28047 non-null  int64  
 10  Type                                    28047 non-null  ob

In [5]:
df = df.drop(columns=["Surfacturation poids","Stockage","ID Expéditeur","Poids (KG)","Livreur","Référence","Client","Téléphone","Adresse","Remarque","Produit","Livreur au rammasage","Ramassage demandé le","Ramassage effectué le","Préparation demandée le","Commande préparée le","Validé par la station de réception le","Validé par admin le","Dispatché à la station de livraison le","Validé par la station de livraison le","Dispatché au livreur le","Feuille de route crée le ","Feuille de route activée le ","Livré le","Encaissé le","Versé à l'admin le","Payé le","Archivé le","Retour demandé le","Transféré vers l'admin le","Reçu par l'admin le","Transféré au partenaire le","Colis facturé","SMS envoyés","Livreur payé","Station départ","Station déstination"])

In [ ]:
df = df.drop(columns=["Station départ","Station déstination"])

In [8]:
df = df.drop(columns=["Commercial"])

In [9]:
df.head()

Tracking      Commune       Wilaya  Montant       Type  \
0  EC0EEE25042244440      Tebessa      Tébessa        0  Livraison   
1  EC0EEE25050445827         Oran         Oran        0  Livraison   
2  EC0EEE25050646042        Arzew         Oran        0  Livraison   
3  EC0EEE25050646061  Constantine  Constantine        0  Livraison   
4  EC0EEE25051547274         Oran         Oran        0  Livraison   

   Préstation Expéditeur Montant retenu Extra retenu  Commission sur colis  \
0   STOP DESK  S3D ECOLE            400          NaN                   NaN   
1   STOP DESK  S3D ECOLE            400          NaN                   NaN   
2  A domicile  S3D ECOLE            850          NaN                   NaN   
3   STOP DESK  S3D ECOLE            400          NaN                   NaN   
4  A domicile  S3D ECOLE            850          NaN                   NaN   

  Type de retenu Rémunérations livreur  Surfacturation livreur  \
0     Periodique                   350                     NaN   
1     Periodique                   350                     NaN   
2     Periodique                   550                     NaN   
3     Periodique                   350                     NaN   
4     Periodique                   550                     NaN   

  Type de retenu livreur        Expédié le Statut  
0            À la source  22-04-2025 15:08  livré  
1            À la source  07-05-2025 20:09  livré  
2            À la source  06-05-2025 09:16  livré  
3            À la source  06-05-2025 11:23  livré  
4            À la source  15-05-2025 13:08  livré

In [10]:
df["Montant retenu"].unique()

array([400, 850, 650, 1100, '/', 800, 500, 900, 250, 1600, 1200, 0, 600,
       700, 1825, 'Non configuré', 300, 1500, 550, 750, 450, 350, 1050,
       1000, 480, 2075, 575, 100, 1800, 730, 1300, 950, 620, 630, 530,
       540, 830, 6500, 7500, 2200, 1250, 1450, 1075, 2450, 2100, 1350,
       1700, 1400, 2000, 2250, 1650, 780, 625, 1610], dtype=object)

In [12]:
df['Montant retenu'] = df['Montant retenu'].replace(['Non configuré', '/', np.nan], 0)

In [13]:
df["Montant retenu"].unique()

array([ 400,  850,  650, 1100,    0,  800,  500,  900,  250, 1600, 1200,
        600,  700, 1825,  300, 1500,  550,  750,  450,  350, 1050, 1000,
        480, 2075,  575,  100, 1800,  730, 1300,  950,  620,  630,  530,
        540,  830, 6500, 7500, 2200, 1250, 1450, 1075, 2450, 2100, 1350,
       1700, 1400, 2000, 2250, 1650,  780,  625, 1610])

In [14]:
df["Montant retenu"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 28047 entries, 0 to 28046
Series name: Montant retenu
Non-Null Count  Dtype
--------------  -----
28047 non-null  int64
dtypes: int64(1)
memory usage: 219.2 KB


In [15]:
df["Commission sur colis"].unique()

array([ nan, 191., 311., 291., 241., 320., 240., 281., 181., 321., 300.,
       323., 331., 251.,   0., 261., 411., 421., 494., 352., 362., 313.,
       294., 314., 273., 271., 193., 293., 194., 282., 302., 250., 290.,
       310., 283., 263., 190., 551., 171., 253., 121., 211., 260., 161.,
       270., 891., 312., 182., 123., 301., 306., 231., 631., 120., 341.,
       280., 180., 242., 110., 391., 573., 213., 160., 173., 163., 221.,
       151., 183., 252., 236., 243., 674., 103., 333., 330.,  22.,  45.,
        29.])

In [16]:
df['Commission sur colis'] = df['Commission sur colis'].replace(np.nan, 0)
df["Commission sur colis"].astype(int)

0        0
1        0
2        0
3        0
4        0
        ..
28042    0
28043    0
28044    0
28045    0
28046    0
Name: Commission sur colis, Length: 28047, dtype: int64

In [17]:
df["Commission sur colis"].astype("str")

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
28042    0.0
28043    0.0
28044    0.0
28045    0.0
28046    0.0
Name: Commission sur colis, Length: 28047, dtype: object

In [18]:
df['Commission sur colis'] = df['Commission sur colis'].astype(str).str.replace('.', '', regex=False).astype(int)
df['Commission sur colis'] = df['Commission sur colis']/10
df['Commission sur colis'] = df['Commission sur colis'].astype(int)

In [19]:
df["Commission sur colis"].unique()

array([  0, 191, 311, 291, 241, 320, 240, 281, 181, 321, 300, 323, 331,
       251, 261, 411, 421, 494, 352, 362, 313, 294, 314, 273, 271, 193,
       293, 194, 282, 302, 250, 290, 310, 283, 263, 190, 551, 171, 253,
       121, 211, 260, 161, 270, 891, 312, 182, 123, 301, 306, 231, 631,
       120, 341, 280, 180, 242, 110, 391, 573, 213, 160, 173, 163, 221,
       151, 183, 252, 236, 243, 674, 103, 333, 330,  22,  45,  29])

In [22]:
df["Type de retenu"].astype("category")

0         Periodique
1         Periodique
2         Periodique
3         Periodique
4         Periodique
            ...     
28042    A la source
28043    A la source
28044    A la source
28045    A la source
28046    A la source
Name: Type de retenu, Length: 28047, dtype: category
Categories (2, object): ['A la source', 'Periodique']

In [23]:
df["Type de retenu"].unique()

array(['Periodique', 'A la source'], dtype=object)

In [24]:
df["Surfacturation livreur"].unique()

array([ nan, 200., 300., 250., 600.])

In [25]:
df['Surfacturation livreur'] = (
    df['Surfacturation livreur']
    .astype(str)
    .str.replace('.', '', regex=False)
    .replace('nan', '0')  # This handles string "nan"
    .astype(int)
)
df['Surfacturation livreur'] = df['Surfacturation livreur']/10
df['Surfacturation livreur'] = df['Surfacturation livreur'].astype(int)

In [26]:
df["Surfacturation livreur"].unique()

array([  0, 200, 300, 250, 600])

In [9]:
df["Extra retenu"].unique()

array([nan, '/', -700, 3550, 0, 2000, 600, 200, 400], dtype=object)

In [10]:
df['Extra retenu'] = (
    df['Extra retenu']
    .astype(str)
    .str.replace('.', '', regex=False)
    .str.replace('/','0', regex=False)
    .replace('nan', '0')  
    .astype(int)
)
df['Extra retenu'] = df['Extra retenu']
df['Extra retenu'] = df['Extra retenu'].astype(int)

In [11]:
df["Extra retenu"].unique()

array([   0, -700, 3550, 2000,  600,  200,  400])

In [27]:
df[["Montant retenu","Extra retenu","Commission sur colis"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28047 entries, 0 to 28046
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Montant retenu        28047 non-null  int64 
 1   Extra retenu          2034 non-null   object
 2   Commission sur colis  28047 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 657.5+ KB


In [206]:
df[['Montant retenu', 'Extra retenu','Commission sur colis']] = df[['Montant retenu', 'Extra retenu','Commission sur colis']].astype(int)

In [207]:
df[['Statut', 'Type de retenu',"Préstation",'Type','Commune',"Wilaya"]] = df[['Statut', 'Type de retenu',"Préstation","Type",'Commune',"Wilaya"]].astype('category')

In [210]:
df["Rémunérations livreur"].unique()

array([  350,   550,   450,     0,   570,  2650,   300,   600,  1200,
         650,   150,  1050,   400,   800,   700,   500,   720,  2800,
         900,   750,  1150,   950,  1650,  4650,   850,  1800,  1500,
        2000,  1100,  1600,   200,  1300,   250,  1000,  7400, 45350,
        1700,  1850,  3600,   620,   585,   640,   420,   830,   525,
        1275,  1175,   725,   745,   775,   825,  2150,  1350])

In [209]:
df['Rémunérations livreur'] =df['Rémunérations livreur'].astype(str).str.replace('Non configuré', '0', regex=False).replace('nan', '0').astype(int)

df['Rémunérations livreur'] = df['Rémunérations livreur'].astype(int)

In [214]:
df["Expéditeur"] = df["Expéditeur"].astype("category")
df["Type de retenu livreur"] = df["Type de retenu livreur"].astype("category")

In [216]:
df["Station départ"].unique()

array(['Hub Principal'], dtype=object)

In [219]:
df["Expédié le"] = pd.to_datetime(df["Expédié le"], format='%d-%m-%Y %H:%M')

In [235]:
df["Expédié le"] = pd.to_datetime(df["Expédié le"], dayfirst=True)

# Extract only date (year, month, day)
df["Expédié le"] = df["Expédié le"].dt.date

In [241]:
df["Expédié le"] = pd.to_datetime(df["Expédié le"], dayfirst=True)

# Keep only the date part but preserve datetime64 dtype
df["Expédié le"] = df["Expédié le"].dt.floor("D")


In [237]:
df["Expédié le"].head(2)

0    2025-04-22
1    2025-05-07
Name: Expédié le, dtype: object

In [242]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28047 entries, 0 to 28046
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   Tracking                28047 non-null  object        
 1   Commune                 28047 non-null  category      
 2   Wilaya                  28047 non-null  category      
 3   Montant                 28047 non-null  int64         
 4   Type                    28047 non-null  category      
 5   Préstation              28047 non-null  category      
 6   Expéditeur              28047 non-null  category      
 7   Montant retenu          28047 non-null  int64         
 8   Extra retenu            28047 non-null  int64         
 9   Commission sur colis    28047 non-null  int64         
 10  Type de retenu          28047 non-null  category      
 11  Rémunérations livreur   28047 non-null  int64         
 12  Surfacturation livreur  28047 non-null  int64 

In [243]:
df.to_excel("C:\Amine\Projects\Delivery company\ofiltered_data.xlsx", index=False)

In [246]:
df.to_csv("C:/Amine/Projects/Delivery company/filtered_data.csv", index=False, encoding="utf-8")